### ISSUE TITLE
kscreenshot: make JPEG save as .jpg not .jpeg

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-ideas#13]

**Comment by davidedmundson** [comment]
It turns out Qt loads the mimetype extension from a global shared mime database in /usr/share/mime 
Each extension (glob) is apparently ordered, so it's by freedesktop.org design that .jpeg is selected first. 

It's easy enough to override, we just need to put this file into /usr/share/mime/package 
https://paste.kde.org/pice1vjjg as AAfreedesktop_changes.org.xml
(note that name name is important, it needs to be alphabetically before the real freedesktop.org.xml file)

Then run "sudo update-mime-database /usr/share/mime" 
(if this file existed at install time, this line won't be needed)

Fixing it this way has the advantage that then you'll adjust the default filename in:
 Gwenview, krita and digikam, screenie at the same time which seems neater than only fixing ksnapshot.

**Comment by star-buck** [comment]
needs more global solution than kscreenshot, also now spectacle, so closing this here.
